CREATE TABLE `USER` (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	email VARCHAR(60) NOT NULL, 
	`password` VARCHAR(50) NOT NULL,
	timesVisited INT NOT NULL
);

CREATE TABLE `TESTSET` (
    title VARCHAR(20) NOT NULL PRIMARY KEY,
	content TEXT NOT NULL  
);

CREATE TABLE `TRAINSET` (
    title VARCHAR(20) NOT NULL PRIMARY KEY,
	content TEXT NOT NULL  
);

CREATE TABLE `PARAMETER_FILE` (
    title VARCHAR(20) NOT NULL PRIMARY KEY,
	content TEXT NOT NULL  
);

CREATE TABLE `LOGFILE` (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `datetime` DATETIME NOT NULL, 
    parameter_id VARCHAR(20) NOT NULL,
    trainset_id VARCHAR(20) NOT NULL,
    testset_id VARCHAR(20) NOT NULL
);


